# Generated by Django 4.0.6 on 2022-09-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_place_amenity_place_tourism'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='office',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='amenity',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='tourism',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
