# Generated by Django 4.0.6 on 2022-12-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_place_office_alter_place_amenity_alter_place_tourism'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(default=None, max_length=255),
        ),
    ]
