# Generated by Django 4.0.6 on 2022-09-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipality',
            old_name='location',
            new_name='boundaries',
        ),
    ]
