# Generated by Django 4.0.6 on 2022-09-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_rename_location_municipality_boundaries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='location',
            new_name='boundaries',
        ),
    ]
